#!/usr/bin/env ruby

require 'time'
require 'fileutils'

FIVE_MINUTES = 5 * 60

while true
	now = Time.new
	path = File.expand_path ".", "#{now.year}/#{now.month}/#{now.day}"
	puts path
	FileUtils::mkdir_p path unless File.directory? path

	hour_str = "0" * (2 - now.hour.to_s.length) + now.hour.to_s
	min_str  = "0" * (2 - now.min.to_s.length) + now.min.to_s
	image_name = "#{path}/#{hour_str}#{min_str}.jpg"
	puts `./imagesnap -1 #{image_name}`

	sleep FIVE_MINUTES
end